### ISSUE TITLE
64bit dll-s

### ISSUE THREAD

**Issue by ittisvagyok** [sreckolipovsek/KaliopaMobileViewer#1]
Dear Obcina Team!

I was wondering if the dll's related to KaliopaMobileviewer could be accessible in 64bit. Or is there another way to make it work on 64bit Mapguide?

Thank you in advance if you reply, i know this is an open source project, so i'll try not to ask questions...

**Comment by sreckolipovsek** [comment]
Hi, just put all dll files from your x64 ($\Web\www\mapviewernet\bin) to bin folder in this aplication and it should work. You should also have to check if your settings in IIS are right (Enable32 bit applications = false in Application Pool that this application is running on).

**Comment by ittisvagyok** [comment]
Hi,

Thanky you for the reply, it is much appreciated. Our problem is, that we
cannot disable 32bit applications, since it is necessary for other dlls to
run in the application we wanted integrate Kaliopa into.

Anyway, this was an important piece of information for us.

Best regards and good job on the viewer, thanks for the support,
Gábor Grósz
HungaroCAD Ltd.
grosz.gabor@hungarocad.hu

2015-04-09 14:41 GMT+02:00 Srečko Lipovšek notifications@github.com:

**Comment by sreckolipovsek** [comment]
Hi Gabor,

You can simpy create new Application Pool in IIS and than Assign that application pool to this Application.
1. ```
     In IIS go to Application Pool -> Add Application Pool (make shure that you pick right .NET frameork and disable 32bit application)
   ```
2. ```
     Assign that Application pool to your application
   ```

a.       If appplication is already created: right click on application -> Manage Application -> Advanced Settings -> Pick your Newly Created Application Pool

b.      If application is NOT yet created: when creating application -> Create Application -> Pick your Newly Created Application Pool

Each New application Pool created in IIS is reflected in running services. New w3wp service is running for each Application Pool.

Hope it helps.
Have a nice day.

**Comment by ittisvagyok** [comment]
Hi Srečko,

Thank you for your help (again and again), we managed to integrate it
yesterday :)

We have another application, which made it harder to implement it,
otherwise it worked like a charm out of the box, following the readme.

Best regards, Gabor

2015-04-15 8:44 GMT+02:00 Srečko Lipovšek notifications@github.com:
