### ISSUE TITLE
AIMS 2014 to AIMS 2017 upgrade with Kaliopa Mobile Viewer Errors

### ISSUE THREAD

**Issue by RenoSun** [sreckolipovsek/KaliopaMobileViewer#2]
Hi @sreckolipovsek , 

I am trying to upgrade our AIMS 2014 to AIMS 2017, and trying to figure the 
errors using the Kaliopa Mobile Viewer as following: 

Problem:\nThe connection to the Infrastructure Map Server is not open as 
expected.\n\nPossible Causes:\n-Your session has been idle for too 
long;\n-Infrastructure Map Server is no longer responding;\n-Internet 
connection problems.\n\nSolution:\nRestart your application / session, 
restart the Infrastructure Map Server service, or contact with the server 
administrator. 

http://osgeo-org.1560.x6.nabble.com/AIMS-2014-to-AIMS-2017-upgrade-with-Kaliopa-Mobile-Viewer-Errors-td5342804.html

Really appreciate any suggestions and solutions.

**Comment by sreckolipovsek** [comment]
Hi,

New version bring change in Map.Open() method.
Just remove resourceService parameter and it should work.

Also I think that Map.Save method have some changes.
Look at mapviewernet folder how they are used.



Poslano iz pametnega telefona Samsung Galaxy.

**Comment by RenoSun** [comment]
Hi @sreckolipovsek ,

Thank you for your help!

In order to make all things working for the newer version, we will have to use following codes:

Replace codes:
`        MgUserInformation userInfo = new MgUserInformation(sessionId);
        MgSiteConnection site = new MgSiteConnection();`
with
`        MgUserInformation userInfo = new MgUserInformation();
        userInfo.SetMgSessionId(sessionId);
        MgSiteConnection site = new MgSiteConnection();
        site.Open(userInfo);`

Replace `map.Open(resourceService, mapName);`
with
`map.Open(mapName);`

Replace `map.Save(resourceService)`
with
`map.Save();`
Thank you for you helps!!! It's time to rock with Kaliopa Mobile Viewer again!
